### ISSUE TITLE
aggtarget with small dataframe

### ISSUE THREAD

**Issue by jeromedockes** [skrub-data/skrub#1018]
### Describe the bug

while investing #1005 I got an unrelated error with aggtarget. I think it only happens for super small dataframes so probably not important but I'm opening an issue to keep track of it in case it pops up again anyway

### Steps/Code to Reproduce

```python
import numpy as np
import pandas as pd
from skrub import AggTarget

X = pd.DataFrame(dict(a=[1, 2, 1]))
y = np.array([100., -10.0,200.0 ])

AggTarget(main_key="a", operation=["hist(2)"]).fit_transform(X, y)
```

### Expected Results

no error

### Actual Results

```
Traceback (most recent call last):
  File "/home/jerome/workspace/scratch/2024/07/scratch.py", line 8, in <module>
    AggTarget(main_key="a", operation=["hist(2)"]).fit_transform(X, y)
  File "/home/jerome/.virtualenvs/skrub/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/jerome/.virtualenvs/skrub/lib/python3.10/site-packages/sklearn/base.py", line 1101, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/home/jerome/workspace/backedup_repositories/skrub/skrub/_agg_joiner.py", line 480, in fit
    self.y_ = skrub_px.aggregate(
  File "/home/jerome/workspace/backedup_repositories/skrub/skrub/_dataframe/_pandas.py", line 136, in aggregate
    serie_group = table.groupby(key)[col_to_agg].value_counts(**kwargs)
  File "/home/jerome/.virtualenvs/skrub/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 857, in value_counts
    sorter = np.lexsort((out if ascending else -out, left[0]))
ValueError: all keys need to be the same shape
```

### Versions

I can reproduce it with skrub `1.0.0` or the main branch

### pandas

I guess this is an issue in pandas?

```python
import pandas as pd

df = pd.DataFrame(dict(y=[100, -10, 200], a=[1, 2, 1]))
df.groupby('a')['y'].value_counts(bins=[-10.,  95., 200.])
```

```
Traceback (most recent call last):
  File "/home/jerome/workspace/scratch/2024/07/value_counts.py", line 4, in <module>
    df.groupby('a')['y'].value_counts(bins=[-10.,  95., 200.])
  File "/home/jerome/.virtualenvs/skrub/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 857, in value_counts
    sorter = np.lexsort((out if ascending else -out, left[0]))
ValueError: all keys need to be the same shape

```
```

**Comment by TheooJ** [comment]
Closing since `hist` is no longer supported in `AggTarget` (https://github.com/skrub-data/skrub/pull/1116)
